#!/bin/dash
# SPDX-License-Identifier: GPL-2.0-or-later

set -ex

diskname=$1

# Dump u-boot image...
#
# 0x000000 - 0x0001B7 Bootloader (440 bytes) First part of uboot
# 0x0001B8 - 0x0001FF Signature and Partition table
# 0x000200 - 0x100000 Free space for second part of uboot
# 0x100000 - xxxxxxxx Boot partition
#
dd if=usr/lib/u-boot/qemu_arm64/u-boot.bin of=$diskname conv=notrunc bs=256 count=1 seek=0
dd if=usr/lib/u-boot/qemu_arm64/u-boot.bin of=$diskname conv=notrunc bs=512 seek=1 skip=1
